use_frameworks!

platform :ios, '11.0'

inhibit_all_warnings!
install! 'cocoapods',
  disable_input_output_paths: true,
  generate_multiple_pod_projects: true

source 'https://github.com/CocoaPods/Specs.git'

target 'TheRouterSwift_Example' do
  pod 'TheRouterSwift', :path => '../'
  pod 'SnapKit', '5.6.0'
  pod 'Toast', '4.0.0'
  pod 'JKSwiftExtension'

  target 'TheRouterSwift_Tests' do
    inherit! :search_paths

    
  end
end
